apiVersion : v1
kind : Pod
metadata:
  name: kubecli
  labels:
    app: kubecli
spec:
  containers:
  - name: kubecli-container
    image: kubecli:latest
    imagePullPolicy: Never
    volumeMounts:
    - mountPath: /root/.kube
      name: kubeconfig
    ports:
    - containerPort: 9011
  volumes:
  - name: kubeconfig
    hostPath:
      path: /root/.kube
      type: DirectoryOrCreate