apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv0003
    labels:
      release: "stable"
spec:
    capacity:
      storage: 10Mi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    storageClassName: slow
    hostPath:
      path: /home/test
      type: DirectoryOrCreate
      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"
---
apiVersion: v1
kind: Pod
metadata:
    name: mypod
spec:
    containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
    volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim